export const UPDATE_COUNT = 'UPDATE_COUNT';
export const API_CALL = 'API_CALL';
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const VIEW='VIEW';
export const PARCEL='PARCEL';
export const ADDPARCEL='ADDPARCEL';
export const DELETE='DELETE';
export const UPDATE='UPDATE';
